# Generated by Django 5.2.3 on 2025-06-28 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, help_text='Límite máximo de gastos por mes en euros', max_digits=10, verbose_name='Límite Mensual')),
                ('warning_percentage', models.PositiveIntegerField(default=75, help_text='Porcentaje del límite para mostrar alerta amarilla (ej: 75)', verbose_name='Porcentaje de Alerta')),
                ('critical_percentage', models.PositiveIntegerField(default=90, help_text='Porcentaje del límite para mostrar alerta roja (ej: 90)', verbose_name='Porcentaje Crítico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
            },
        ),
    ]
