# Generated by Django 5.2.3 on 2025-06-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='email_alerts_enabled',
            field=models.BooleanField(default=False, help_text='Recibir notificaciones por email al superar el porcentaje crítico', verbose_name='Alertas por Email'),
        ),
    ]
